###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build python
        run: |
          docker build ./python -t ulihorn/python:1.0.0
